app/cart/urls.py
from django.urls import path
from .views import (cart_detail, update_cart_by_front,
                    remove_product, remove_cart, get_cart_length,
                    remove_product_ajax)


urlpatterns = [
    path('detail/', cart_detail, name="cart_detail"),
    path('update_cart_session/', update_cart_by_front, name="update_cart_session"),
    path('remove_fetch/', remove_product_ajax, name="remove_product_ajax"),
    path('remove/<int:product_id>/', remove_product, name="remove_product"),
    path('clear/', remove_cart, name="remove_cart"),
    path('length/', get_cart_length, name="cart_length"),

]

app/users/urls.py
from django.urls import path
from .views import register, log_in, log_out, user_detail

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>/', user_detail, name='detail'),
    # path('change_password/', change_password, name='change_password'),
]

app/website_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.views import AdminTemplateView, ProductListByCategory
from orders.views import all_orders_list

urlpatterns = [
    path('staff/orders/', all_orders_list, name="admin_all_orders"),
    path('staff/', AdminTemplateView.as_view(), name="admin-page"),
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', ProductListByCategory.as_view(), name='main')
]

app/templates/503.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block title %}
    <title>Магазин товаров</title>
    {% endblock title %}
</head>
<body>
    <header>
        <nav class="navbar">
            <ul>
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'categories' %}">Категории</a></li>
                <li><a href="{% url 'products' %}">Товары</a></li>
                <li><a href="#">О нас</a></li>
                <li><a href="#">Контакты</a></li>
                {% if cart|length != 0 %}
                <li><a href="{% url 'cart_detail' %}">Корзина (<span id="cartLengthHeader">{{cart|length}}</span>)</a></li>
                {% else %}
                <li><a href="{% url 'cart_detail' %}">Корзина <span id="cartLengthHeader"></span></a></li>
                {% endif %}
                <li><a href="{% url 'orders' %}">Заказы</a></li>
                {% if request.user.id %}
                <li><a href="{% url 'users:detail' request.user.id %}">{{request.user}}</a></li>
                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">Войти</a></li>
                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <form action="{% url 'product_search' %}" method="get" style="margin-top:10px; margin-left:20px">
        <input type="search" name="query">
        <button type="submit">Поиск</button>
    </form>

    {% block content %}
    {% endblock content%}

    <footer class="footer__new">
        <p>Контактные данные: info@example.com | Телефон: +7 (123) 456-78-90</p>
    </footer>
</body>
</html>

app/templates/base_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock title %}
</head>
<body>
{% block header %}
{% endblock header %}

{% block content %}
{% endblock content %}

{% block footer %}
{% endblock footer %}
</body>
</html>